<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date of Discharge</name>
   <tag></tag>
   <elementGuidId>4718a348-0f62-4644-8136-584000f8d17c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_DofDischarge']/div/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_currentPage_allQuestions_0__answers_0__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff6bc4c8-9b3e-447a-9939-1c5b3aff00d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>067ae96d-6659-4ab7-8729-397d4294d600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[0].answers[0].value</value>
      <webElementGuid>bca3a3c3-7661-4279-9194-4dc5496442ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_currentPage_allQuestions_0__answers_0__value</value>
      <webElementGuid>c4f0d0ff-8b22-4a00-840f-6f992759dac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker align-text-center form-control hasDatepicker</value>
      <webElementGuid>40deff11-645a-4527-af6a-9ac6369e4b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_currentPage_allQuestions_0__answers_0__value&quot;)</value>
      <webElementGuid>ce995988-c84b-46ef-91d1-1dd4a0b3ca45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_currentPage_allQuestions_0__answers_0__value']</value>
      <webElementGuid>0304035a-25e2-41d8-98ca-483ee943b4a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_DofDischarge']/div/div[2]/div/div/input</value>
      <webElementGuid>1865628f-d171-4452-ad5a-e2160ffb26e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>90ddff67-3ae5-4333-b610-893c57b47d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[0].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_0__answers_0__value']</value>
      <webElementGuid>38f5e425-770e-4c76-84b5-5bc07b7ec5a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
