<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ServiceConnectedDisabilityGranted Yes</name>
   <tag></tag>
   <elementGuidId>3a2fc2db-2853-4e44-a68a-8bab71518c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_SerConnectDis']/div/div[2]/div/div/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ed7139a-2794-489e-8338-c8c76494630f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>43b280e9-3381-4f91-b7cf-3189324a49a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c2269573-2c60-4f86-8cb9-f4549dbf08a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[2].answers[0].value</value>
      <webElementGuid>d8d421c9-521b-4911-bfd2-65664817f7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentPage.allQuestions[2].answers[0].value-1</value>
      <webElementGuid>2e7b4f91-e985-4e7f-b351-4308565613b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>670ef108-326c-4f13-940a-c92ae4642a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>conditionallyAutoContinue(false);</value>
      <webElementGuid>4e7b829f-79ff-438d-ae07-47bdf68a5af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentPage.allQuestions[2].answers[0].value-1&quot;)</value>
      <webElementGuid>15aeab3a-1487-4616-ba86-daaa0d388232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currentPage.allQuestions[2].answers[0].value-1']</value>
      <webElementGuid>1af004db-578f-4fb5-b03a-b10a3561ec3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_SerConnectDis']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>a310877b-cc9d-4236-bd95-cf31250fca98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>ed2432eb-dc5a-4387-b873-a942a1914d9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'currentPage.allQuestions[2].answers[0].value' and @id = 'currentPage.allQuestions[2].answers[0].value-1']</value>
      <webElementGuid>79bfa697-da10-4646-8fcc-2faa92496707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
