<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Continue App Information</name>
   <tag></tag>
   <elementGuidId>f5a091af-1e14-44de-9e0d-a61b6496c3c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_nextPageContinue_execute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e81bb075-b6ea-4725-89a2-f26b1beb32fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f84c7fbb-795c-461e-8a83-22842e403682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_nextPageContinue_execute</value>
      <webElementGuid>bb9d123f-8e4f-45f7-a991-76f9d172e3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:nextPageContinue!execute</value>
      <webElementGuid>f904a6db-c14a-4c15-82b5-1c74ac2d8a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue ></value>
      <webElementGuid>f468b0bf-ff50-4f1c-8daa-1c0de6ef6a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary</value>
      <webElementGuid>47cc3131-ab1b-41ac-999c-d4dd0cb41fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_nextPageContinue_execute&quot;)</value>
      <webElementGuid>c8059c3e-9cbc-411d-b1d5-22bb5c97e705</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      <webElementGuid>1c386902-0193-48bd-bd48-a173830d5e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-continue']/input</value>
      <webElementGuid>3118d76d-43b7-4364-beb1-286d7e7c2ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>820ab71a-ced5-48d6-9492-89c355af06b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'el-content-form_nextPageContinue_execute' and @name = 'action:nextPageContinue!execute']</value>
      <webElementGuid>2422995a-0992-4229-a573-04e46f5c9fe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
