<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Amount Continued as Term</name>
   <tag></tag>
   <elementGuidId>e67e915b-c080-41ca-95ea-2c0787fab9fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;element-Q_AmtInsContTerm&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element-Q_AmtInsContTerm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0b82b94-00a6-459c-9912-0dc571f8d958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d64929d7-7e9b-47a2-b084-1b7aeeff79d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[3].answers[0].value</value>
      <webElementGuid>e11f287f-a8ec-4582-a8c0-c602e3e39c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_AmtInsContTerm</value>
      <webElementGuid>a91852af-957b-40f6-8985-bcf4518d99d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>468e90c8-c8b5-4def-9b84-f4a717eae49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_AmtInsContTerm&quot;)</value>
      <webElementGuid>263a08b6-4505-425e-ac86-bb1d3ebfb097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_AmtInsContTerm']</value>
      <webElementGuid>c62a679d-383a-4d14-a059-7e4f938f33a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_AmtInsContTerm']/div/div[2]/div/div/input</value>
      <webElementGuid>e1892b64-e18e-46ee-9810-c6117bdf79a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>64be27ac-c023-4384-a416-640ad2bcaeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[3].answers[0].value' and @id = 'element-Q_AmtInsContTerm']</value>
      <webElementGuid>7ab438d9-46e0-4bdb-a5fe-b5863e72c7ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
