<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Amount Cancelled</name>
   <tag></tag>
   <elementGuidId>93eabdb6-be45-4507-a0a3-74903e82b6b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;element-Q_AmtofTermInsCan&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element-Q_AmtofTermInsCan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ecb7235-66c5-4c6b-9a3b-11e208852e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41613df4-fc80-4c3c-b0c5-db239f01cd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[4].answers[0].value</value>
      <webElementGuid>2538ebee-ad8c-4d48-bd01-2619e7131d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_AmtofTermInsCan</value>
      <webElementGuid>67c6f320-3a27-4690-a0b4-9ce1b8d58974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>622b7b30-83f3-4709-b2b1-2b1518c8e41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_AmtofTermInsCan&quot;)</value>
      <webElementGuid>cd5f3232-23da-46ba-91f8-b081326a2b1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_AmtofTermInsCan']</value>
      <webElementGuid>aaa7265c-1b65-46ba-8b04-92258eacfaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_AmtofTermInsCan']/div/div[2]/div/div/input</value>
      <webElementGuid>a8d87e78-9840-422c-a8bc-6a621871cb07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/input</value>
      <webElementGuid>b86b0ce3-560b-4525-bb08-4b20e442132f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[4].answers[0].value' and @id = 'element-Q_AmtofTermInsCan']</value>
      <webElementGuid>f870189f-7b7b-402c-bd34-ac93f8a92038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
