<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Effective Date</name>
   <tag></tag>
   <elementGuidId>085b8dca-024e-4b0c-a03e-9f41c9c6d6c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;el-content-form_currentPage_allQuestions_5__answers_0__value&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_currentPage_allQuestions_5__answers_0__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67bd61ba-2911-4c0d-ae39-a71016d7da2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6f42def-f4a2-4b24-82f1-c753f0afa93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[5].answers[0].value</value>
      <webElementGuid>e66efcee-70b8-468c-9efb-88e2ce4b4026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01/01/2023</value>
      <webElementGuid>f649515d-1ee0-4b29-8b60-da1fe7fd6b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_currentPage_allQuestions_5__answers_0__value</value>
      <webElementGuid>0c72fcff-5af2-41db-9d21-04c6a19bba40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker align-text-center form-control hasDatepicker</value>
      <webElementGuid>ef2fb796-0af0-4103-98be-28c6a7e920dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_currentPage_allQuestions_5__answers_0__value&quot;)</value>
      <webElementGuid>1981e7b9-ec17-4be4-a516-48ee6ab1263f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_currentPage_allQuestions_5__answers_0__value']</value>
      <webElementGuid>72949dc5-215f-463f-b28e-984a0affe2bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_EffectiveDateConv']/div/div[2]/div/div/input</value>
      <webElementGuid>f629516c-c3ea-4c11-b582-d9e0257179e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/input</value>
      <webElementGuid>b13bb064-7af3-415b-a5e8-992f03ce2c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[5].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_5__answers_0__value']</value>
      <webElementGuid>eda42626-b9a7-4a2f-8f94-627148338fdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
