<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Continue button</name>
   <tag></tag>
   <elementGuidId>18445905-507f-4cdd-8f6e-9a473a3d8f6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_nextPageContinue_execute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5d8cb33-d633-4cb6-b512-e29edaaf8f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e104d358-2c9a-466f-853a-10002779e00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_nextPageContinue_execute</value>
      <webElementGuid>97ce41eb-7494-4069-907d-07c446075bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:nextPageContinue!execute</value>
      <webElementGuid>e5362f42-053c-4771-bf4e-269f8f4aed47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue ></value>
      <webElementGuid>80cfb5c7-5a29-4391-a2a6-2efce88d3041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary</value>
      <webElementGuid>4043f3a4-3fc1-4520-9684-568207fe8f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_nextPageContinue_execute&quot;)</value>
      <webElementGuid>e3f74895-a4ef-42b1-b72b-401d7ac1e232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      <webElementGuid>b17e28d5-9155-45e0-9a6e-14026bedfdb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-continue']/input</value>
      <webElementGuid>53692937-3cb8-4a6b-a62c-70d14ef16ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5333a0c2-5b95-452d-84e1-38dfd3e18352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'el-content-form_nextPageContinue_execute' and @name = 'action:nextPageContinue!execute']</value>
      <webElementGuid>7ba910eb-da90-4374-8c62-05120869c3a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
