<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NSC Conditions No</name>
   <tag></tag>
   <elementGuidId>9a7c006a-28e3-4009-979c-fee27f5d5c01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_NSCconditions']/div/div[2]/div/div/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21cc65d2-5cb6-498f-9163-cc40794ce29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b560e72a-8757-4dd3-b065-fd1b9fc9eadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>44330e7f-9b3d-4062-b438-6bbce92dade8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[0].answers[0].value</value>
      <webElementGuid>27f394f4-1119-4347-9631-8644cf490af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentPage.allQuestions[0].answers[0].value-2</value>
      <webElementGuid>04883e62-8e14-4af5-ad61-51de9309858e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>705e97d5-3f7b-4740-b1e8-928a3a8e899b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>conditionallyAutoContinue(false);</value>
      <webElementGuid>6fd538d6-305d-4d8b-bd3f-f0ead7f10115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentPage.allQuestions[0].answers[0].value-2&quot;)</value>
      <webElementGuid>7a31861b-4ac3-4166-980b-58916c49bd82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currentPage.allQuestions[0].answers[0].value-2']</value>
      <webElementGuid>150255b4-798d-4339-ab6f-aff986c6fe31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_NSCconditions']/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>3b642a29-3a87-4c3a-9817-3264fa6fd96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>d00bde20-30b6-4ce2-8c13-e3b3020f04a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'currentPage.allQuestions[0].answers[0].value' and @id = 'currentPage.allQuestions[0].answers[0].value-2']</value>
      <webElementGuid>7d932cd6-b2e3-4c73-881f-fbaee79a01a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
