<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Amount of Insurance</name>
   <tag></tag>
   <elementGuidId>b6784f03-586c-4aa8-a12f-aaf7dd63a591</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-Q_AmtofInsurance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element-Q_AmtofInsurance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9825cc1c-be9e-46a3-b99f-2593b2f5664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42f1fc18-e0fc-4871-b6da-17856804a697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[1].answers[0].value</value>
      <webElementGuid>63c57bfa-18fe-419e-9fdb-be57151e8b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_AmtofInsurance</value>
      <webElementGuid>d4bed270-b29f-45aa-a827-872cca496195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>a1cc60d8-e441-4bce-aa2c-b4b0768ea275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_AmtofInsurance&quot;)</value>
      <webElementGuid>febebf13-7c63-43e0-8211-badbc42fbedf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_AmtofInsurance']</value>
      <webElementGuid>e091ee29-bc25-44c5-8a6c-ffbb34c1e622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_AmtofInsurance']/div/div[2]/div/div/input</value>
      <webElementGuid>ca7ee6cd-63fb-44be-abd6-950601cff8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>50edad37-b984-4b36-8bbe-5720792d07ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[1].answers[0].value' and @id = 'element-Q_AmtofInsurance']</value>
      <webElementGuid>813dd7fa-72bb-40cf-a486-49ea16c6489a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
