<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Effective Date</name>
   <tag></tag>
   <elementGuidId>04abe2af-6b60-4285-98b0-6a2da50efc8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_currentPage_allQuestions_3__answers_0__value</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'currentPage.allQuestions[3].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_3__answers_0__value']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_EffectiveDate']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ae5c9fb-ae20-49ca-b424-eed2b8e27eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3945a830-345f-495a-81a1-1bd47ce0d1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[3].answers[0].value</value>
      <webElementGuid>d5c1a57f-0519-4ab2-9c64-a8d5f8daf12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_currentPage_allQuestions_3__answers_0__value</value>
      <webElementGuid>b8a721f6-154d-4885-b946-2698bcfd4a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker align-text-center form-control hasDatepicker</value>
      <webElementGuid>d22e9d5c-eda1-4001-b79c-da966955792a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_currentPage_allQuestions_3__answers_0__value&quot;)</value>
      <webElementGuid>581e973f-eb2c-47e6-92d9-83fa19fcaa41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_currentPage_allQuestions_3__answers_0__value']</value>
      <webElementGuid>6e258158-ffad-4df3-803f-a3160fa33ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_EffectiveDate']/div/div[2]/div/div/input</value>
      <webElementGuid>59622655-c7f7-40af-a5e9-622a75bb8f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>18d9ef6e-dbf4-4ed6-87dc-55e211394c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[3].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_3__answers_0__value']</value>
      <webElementGuid>b6b5bec5-f077-418e-b7ee-1fb18eb5a553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
