<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NSC Conditions No</name>
   <tag></tag>
   <elementGuidId>05482037-1271-46f7-bae9-b52234577f58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_NSCconditions']/div/div[2]/div/div/div/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ffa9443-2b9b-4a6e-977d-474f43e8b365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8e112d45-8c9c-440e-a6ce-fa5c8c682bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>56b572e0-1e03-4019-9275-ea71df65647c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[0].answers[0].value</value>
      <webElementGuid>e08242c5-6c21-45b2-af43-33e5912c594a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentPage.allQuestions[0].answers[0].value-2</value>
      <webElementGuid>92db0b75-a36a-478a-9fbd-d6576b50514b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>517a427d-71e5-436c-98aa-47afddb1f086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>conditionallyAutoContinue(false);</value>
      <webElementGuid>55bc0896-e05a-448d-80e2-78992b36da5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentPage.allQuestions[0].answers[0].value-2&quot;)</value>
      <webElementGuid>c5016476-7e61-4114-9fb1-7cf33e135e81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currentPage.allQuestions[0].answers[0].value-2']</value>
      <webElementGuid>1cb8c4d8-28b8-4dcd-958b-ec563c52bc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_NSCconditions']/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>232ea9c2-1a8b-45ef-a80a-5b4fc928e80a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>2107c1f7-3381-4bcc-a2d3-03735c57e894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'currentPage.allQuestions[0].answers[0].value' and @id = 'currentPage.allQuestions[0].answers[0].value-2']</value>
      <webElementGuid>34340b21-9db8-481d-ad29-6828c6663139</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
