<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Amount of Insurance</name>
   <tag></tag>
   <elementGuidId>956070d1-02f8-4b1c-aca4-b4bf86ed4146</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='element-Q_AmtofInsurance']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element-Q_AmtofInsurance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fc511ce-c1e0-4fe3-bc8d-42787c62c250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>29a4d56d-9ead-45bd-8bf1-2cc63cc76160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[1].answers[0].value</value>
      <webElementGuid>9c0c34c7-9036-4ef4-8947-fbe5075e1ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_AmtofInsurance</value>
      <webElementGuid>570bd507-a255-414b-8f13-37badef22782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>75e3d1f7-75a5-432c-868a-9e2ddc8f22b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_AmtofInsurance&quot;)</value>
      <webElementGuid>72928e7d-1964-47ee-b4c9-e89bd0b9cfc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_AmtofInsurance']</value>
      <webElementGuid>c268e37b-68f5-4c17-933b-00d2cba535b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_AmtofInsurance']/div/div[2]/div/div/input</value>
      <webElementGuid>f5be964f-640f-49d7-9764-5cfc0a411ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>7ac5039b-8be5-4430-93e2-99c063dc17e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[1].answers[0].value' and @id = 'element-Q_AmtofInsurance']</value>
      <webElementGuid>d5687d2d-745e-4215-a633-61f0d47f5629</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
