<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Application Information Reviewed Yes</name>
   <tag></tag>
   <elementGuidId>5a115595-7b55-41f6-9fb5-cf1f9c44b1fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;div-question-Q_AppInfoReview&quot;]//following::Input[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6798562-b1fb-4e76-9919-306f8062115c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>242712a3-be31-426a-8ff7-19f1782ddf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a44738f6-b833-4734-82c3-1388c75a6f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[6].answers[0].value</value>
      <webElementGuid>b7e2ac9e-882b-49bd-8b1b-ea40888b72a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentPage.allQuestions[6].answers[0].value-1</value>
      <webElementGuid>eb9e8a48-898f-403a-b320-82268b5dd4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>41d88901-e913-4e3a-835a-d00a5288a4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>conditionallyAutoContinue(false);</value>
      <webElementGuid>3764c8e7-1655-4457-93f3-c96bbdea454e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentPage.allQuestions[6].answers[0].value-1&quot;)</value>
      <webElementGuid>cb0665f7-4023-4c94-8403-b703c890de87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currentPage.allQuestions[6].answers[0].value-1']</value>
      <webElementGuid>2d6d8df7-bfb0-4ac0-85de-3ed6e0921485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_AppInfoReview']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>c74594cc-f5b7-43c7-b2f6-058eb0e773f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>51a7063e-4db0-4836-965d-6b3d3ccc71b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'currentPage.allQuestions[6].answers[0].value' and @id = 'currentPage.allQuestions[6].answers[0].value-1']</value>
      <webElementGuid>0f39e192-8a79-44fb-9caa-27a9578d5538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
