<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Continue button</name>
   <tag></tag>
   <elementGuidId>c4edecf9-c196-46d6-8f7f-c75bfc8b40a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_nextPageContinue_execute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cd1f852-f1ef-41ee-b311-820598a01c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2e0f7ff7-cd10-436d-b07f-f0a550d37bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_nextPageContinue_execute</value>
      <webElementGuid>47b48d0e-9009-4975-9316-67ed7d57ce5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:nextPageContinue!execute</value>
      <webElementGuid>f0c4e485-3697-4fb5-bc44-f0e0d9e782ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue ></value>
      <webElementGuid>f4da3ab2-d39d-480f-8497-b4cebb1644b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary</value>
      <webElementGuid>9aa0b2b0-67cd-47ff-bae9-0183ed0e8b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_nextPageContinue_execute&quot;)</value>
      <webElementGuid>e6171c05-d25a-4859-85b9-21dddc91389f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      <webElementGuid>3f6e6131-2793-4950-9f27-5eeff9f6952f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-continue']/input</value>
      <webElementGuid>0da66723-2da0-42fd-943d-18df604b6a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>a2071020-8cb1-47e8-811d-5c175ab221a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'el-content-form_nextPageContinue_execute' and @name = 'action:nextPageContinue!execute']</value>
      <webElementGuid>a9eab9a0-2e23-4209-9311-535ae1d1f6a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
