<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Effective Date</name>
   <tag></tag>
   <elementGuidId>170fea37-d061-4f00-94b6-a48bb0c3fccc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_currentPage_allQuestions_3__answers_0__value</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @name = 'currentPage.allQuestions[3].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_3__answers_0__value']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_EffectiveDate']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea612660-e032-46eb-922d-b57f8a4a3072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fa0e1ed-dc4d-4054-80ac-25fa0a2194bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[3].answers[0].value</value>
      <webElementGuid>68fe745a-9946-4e53-8495-8becc76f3e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_currentPage_allQuestions_3__answers_0__value</value>
      <webElementGuid>dd1f6a5e-af0b-44a6-9e33-c3a95efac3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker align-text-center form-control hasDatepicker</value>
      <webElementGuid>7d0eea58-3f6b-4978-810c-880970a2e67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_currentPage_allQuestions_3__answers_0__value&quot;)</value>
      <webElementGuid>43684f9a-16b3-452f-9705-a638970c83d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_currentPage_allQuestions_3__answers_0__value']</value>
      <webElementGuid>378dba18-8726-4e2e-b128-eb7bcc4cd467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_EffectiveDate']/div/div[2]/div/div/input</value>
      <webElementGuid>01e43db2-10a3-4e41-88e7-9edf18d0b0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>242ada2e-f19d-43a7-891a-1a0ff7e045b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[3].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_3__answers_0__value']</value>
      <webElementGuid>4c797cee-7d93-4819-a09f-4fd04094a118</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
