<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nothing found to display_methodexecuteOnce</name>
   <tag></tag>
   <elementGuidId>c52319bf-8e9a-4394-ac71-c20d7438e761</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startInterview_startInterview_submit_save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startInterview_startInterview_submit_save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3e40ea51-6a04-4ca7-af0e-770be733a591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b07641ff-a7c3-4a5e-b06b-114ae9db2884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Start ></value>
      <webElementGuid>307fcb23-5ea8-415d-836f-158e1243f558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startInterview_startInterview_submit_save</value>
      <webElementGuid>fc65bed7-eb6e-495d-83f4-ab303c1ab635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>method:executeOnce</value>
      <webElementGuid>af5f1417-8da4-43c6-a882-e3e083ee667a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right el-button ui-state-default ui-corner-all ui-button ui-widget ui-state-hover ui-state-focus</value>
      <webElementGuid>3c9b048e-4327-4cd2-a494-db474ac3627d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6067d302-fd11-43c2-8aff-e40ce4d3a948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1aa421ea-31d0-431e-a879-797cd6a05b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startInterview_startInterview_submit_save&quot;)</value>
      <webElementGuid>428e45e0-4c67-442c-9308-afebeb9515be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startInterview_startInterview_submit_save']</value>
      <webElementGuid>b943469a-704d-4b48-848c-109bb872ddb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_startInterview_startInterview_submit_save']/input</value>
      <webElementGuid>c0a54864-19ab-4192-b156-b4bbc40f1ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7bc5fcc6-2403-466f-97d1-08af7c4f7b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'startInterview_startInterview_submit_save' and @name = 'method:executeOnce']</value>
      <webElementGuid>4def8367-b620-4e4c-9fe0-788596ace626</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
