<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SG_INPUT5_interview.readOnlyScores4.t_0f582a</name>
   <tag></tag>
   <elementGuidId>e4188812-e37a-4fbb-9764-def9a16d5713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startInterview_interview_readOnlyScores_4__totalString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startInterview_interview_readOnlyScores_4__totalString</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e154fb43-a4de-4093-b624-3462ca44782f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>889ece4e-958b-440f-b509-bab3ab09dee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interview.readOnlyScores[4].totalString</value>
      <webElementGuid>6b74c495-c60b-4b34-9aea-14701c9da3bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startInterview_interview_readOnlyScores_4__totalString</value>
      <webElementGuid>5713ba5e-e392-46f8-8b85-493af6e7f502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startInterview_interview_readOnlyScores_4__totalString&quot;)</value>
      <webElementGuid>b22dffe8-310b-442b-a576-c3fd455e5ee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startInterview_interview_readOnlyScores_4__totalString']</value>
      <webElementGuid>13340d50-676f-4c37-b2a9-19126f1d6c67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='score']/tbody/tr[5]/td[3]/input</value>
      <webElementGuid>20cd4838-0132-4c9c-97c0-b2783d7969b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/input</value>
      <webElementGuid>3f93aa0a-6eb3-4c04-a7d0-438f4a0c82db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'interview.readOnlyScores[4].totalString' and @id = 'startInterview_interview_readOnlyScores_4__totalString']</value>
      <webElementGuid>5fc32fa1-523d-4497-aa00-3f4e0e1a2a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
