<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Document ID_interview.readOnlyScores0_ebbbaa</name>
   <tag></tag>
   <elementGuidId>a03dacf7-3a79-4ec1-923d-730055fc8306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startInterview_interview_readOnlyScores_0__totalString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startInterview_interview_readOnlyScores_0__totalString</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e7fd1cb-26a9-4625-a442-43bddc2e87c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fe0683f-1d58-4afa-abc3-8bcc0ca766b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interview.readOnlyScores[0].totalString</value>
      <webElementGuid>d7e285c6-d042-4ca3-bf38-de704cff1301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startInterview_interview_readOnlyScores_0__totalString</value>
      <webElementGuid>cb400aac-8471-4e60-832f-1e52faed8889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startInterview_interview_readOnlyScores_0__totalString&quot;)</value>
      <webElementGuid>8e86f6e2-57d8-4ed4-b324-f95e5e76f1e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startInterview_interview_readOnlyScores_0__totalString']</value>
      <webElementGuid>b99c68cd-c504-48cb-aa68-7ccba5585b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='score']/tbody/tr/td[3]/input</value>
      <webElementGuid>86a1cd1c-9ef4-4120-a8ac-904390eca9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>4b5c3566-36af-4292-a823-1605d077ce02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'interview.readOnlyScores[0].totalString' and @id = 'startInterview_interview_readOnlyScores_0__totalString']</value>
      <webElementGuid>aeddd653-9d83-4c25-bd04-ef9e7045419c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
