<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Document System of Record - sql,onbas_c8c9a2</name>
   <tag></tag>
   <elementGuidId>1f1c5a00-791a-47cb-baff-64e99b1bf558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startInterview_interview_readOnlyScores_1__totalString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startInterview_interview_readOnlyScores_1__totalString</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4bd1739b-cafe-488f-8aa8-1435d3bc77af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b2a98fb0-21a7-406f-822d-fbfae6a42eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interview.readOnlyScores[1].totalString</value>
      <webElementGuid>db038d3e-23ac-4983-8f83-455689b6c76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startInterview_interview_readOnlyScores_1__totalString</value>
      <webElementGuid>d19d436b-ce34-4f8f-9b20-7ef146a3fbc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startInterview_interview_readOnlyScores_1__totalString&quot;)</value>
      <webElementGuid>490058b8-ed64-4e82-b2cb-8012c9786eeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startInterview_interview_readOnlyScores_1__totalString']</value>
      <webElementGuid>62f4fd8f-046c-468d-909b-407b174df92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='score']/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>5786d013-1297-456b-a122-73603a431c88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>22ee9d1e-1e97-4d1b-b1fa-2997a4203313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'interview.readOnlyScores[1].totalString' and @id = 'startInterview_interview_readOnlyScores_1__totalString']</value>
      <webElementGuid>774a28b2-38ec-461a-9a60-ac47bdb5c125</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
