<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference_reference</name>
   <tag></tag>
   <elementGuidId>32bf8296-203c-4b21-b7ac-ad2467298342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#reference</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='reference']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3a42e75-ecb4-4ccd-9d93-df15127ef826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7e58697-ff76-4fae-b5a1-607bcd8c63ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>d05f4eea-c8c8-4e47-8746-9cc257fd347f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>reference</value>
      <webElementGuid>a851f6be-05a6-4883-b63a-a1bad4cb4e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>aad54810-1521-494f-8324-0d354ca0b531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;reference&quot;)</value>
      <webElementGuid>1c724005-b161-476a-9739-3bf7e318e752</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='reference']</value>
      <webElementGuid>36828d7c-cafa-4df9-aced-7fa3eafc2d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_reference']/input</value>
      <webElementGuid>990201a8-2f67-4742-9543-de226d3888b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>2e0bbfee-bee0-463b-9adb-c5eb2d42eb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'reference' and @id = 'reference']</value>
      <webElementGuid>23175393-63c2-4c4d-976e-89a98792e804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
