<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Additional References_actionwo_9eb6ef</name>
   <tag></tag>
   <elementGuidId>10588afb-a523-4dd5-b5bc-4264231c12dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quickActionsForm_workflowSearch_submit_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quickActionsForm_workflowSearch_submit_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c957d982-ccca-4023-8fa6-24ded14c2dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6493fed8-7003-4630-abcc-27b244c407cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>941a46c5-635a-4fff-84f1-99fadfdd6055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quickActionsForm_workflowSearch_submit_search</value>
      <webElementGuid>ef19639a-08c0-4ed5-90eb-37945378ee8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:workflowSearch!search</value>
      <webElementGuid>652fa05b-54af-4196-a9f2-7eef5132f162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right el-button ui-state-default ui-corner-all ui-button ui-widget ui-state-hover ui-state-focus</value>
      <webElementGuid>340960b1-31da-42c3-87a7-e201c894eb30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67f3616d-ca94-4418-b5ad-275d665f424d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>646fb9ce-ef11-49cb-b6ad-f45b09f5f150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quickActionsForm_workflowSearch_submit_search&quot;)</value>
      <webElementGuid>a4030f87-286e-45aa-ad98-1fdc8f14d810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quickActionsForm_workflowSearch_submit_search']</value>
      <webElementGuid>20c578b9-0e38-4bbd-a839-9f28166f319e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_quickActionsForm_workflowSearch_submit_search']/input</value>
      <webElementGuid>53f10df6-795b-4c3f-8a3a-9b10d3bf57ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>368bf2f2-fdb0-4582-82b9-bbce4407c957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'quickActionsForm_workflowSearch_submit_search' and @name = 'action:workflowSearch!search']</value>
      <webElementGuid>70a3f7ea-8e04-47b9-a8d5-6b9f090794c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
