<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_LISSIAflow</name>
   <tag></tag>
   <elementGuidId>8c43b4db-e0b8-438d-b094-d85aa8215675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.el-button.ui-state-default.ui-corner-all.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dashboard-seperator&quot;]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1e935ed-f671-43dd-aed2-1954ed5281a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/workflow/</value>
      <webElementGuid>9cca8979-432b-4abd-ab8e-56da00f8468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>2ac05a5f-0e78-4099-aeb3-d629ad354655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LISSIAflow</value>
      <webElementGuid>77114953-f30f-42da-9f43-8d5aad435e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-seperator&quot;)/ul[1]/li[1]/a[@class=&quot;el-button ui-state-default ui-corner-all ui-state-hover&quot;]</value>
      <webElementGuid>7acf84fd-0ea6-47a1-b0b7-788f8c8c647f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-seperator']/ul/li/a</value>
      <webElementGuid>efb06351-2d74-4582-87ec-0592ac210023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LISSIAflow')]</value>
      <webElementGuid>d5c081b7-56b8-4e00-ad21-41a3b28ef730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you wish to confirm?'])[1]/following::a[2]</value>
      <webElementGuid>656228fb-6cca-49f2-9ebd-a07ac23220a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm!'])[1]/following::a[2]</value>
      <webElementGuid>9be698f6-3686-4b2f-bdca-28fe3239ca38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='uLISSIA'])[1]/preceding::a[1]</value>
      <webElementGuid>556ff1ef-8b74-4622-8bf0-f1be8ad4d00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LISSIADashboard'])[1]/preceding::a[2]</value>
      <webElementGuid>70407560-1dc9-4914-b531-9d69eb7cc8b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LISSIAflow']/parent::*</value>
      <webElementGuid>860a5796-386c-4190-b9b1-38f1534f95ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/workflow/')]</value>
      <webElementGuid>f45bf1c4-1583-490e-b06b-46ee63de946d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>a5d53d05-c456-45a2-b953-0b8222ecdb26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/workflow/' and (text() = 'LISSIAflow' or . = 'LISSIAflow')]</value>
      <webElementGuid>37225c2b-0d51-4ce1-b4d2-f0f4b222bbe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
