<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit</name>
   <tag></tag>
   <elementGuidId>f5e80cb1-664b-4be7-b0e5-f58521b265ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[contains(text(),'ScanningSwRulebook')]//following::td[11]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e8c5e879-66b3-422f-a2aa-4b2f4843f939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/underwriting/rulebook/editRulebook!input.action?rulebookId=5442724</value>
      <webElementGuid>1bfb4bc2-d51c-49a5-ab96-39253f82de1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>270a2efd-1ea1-4d52-85a6-79a3231bbd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rulebook&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[12]/a[1]</value>
      <webElementGuid>24215f26-29e4-4ee6-bba8-3e9eed8d4464</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='rulebook']/tbody/tr[5]/td[12]/a</value>
      <webElementGuid>765e3542-f348-4a42-bd63-9b615d60ca26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit')])[5]</value>
      <webElementGuid>d5fdb494-e032-43dd-b990-a56d39d902dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='None (anyone is permitted access)'])[5]/following::a[5]</value>
      <webElementGuid>ba57af5c-2716-4e8a-84d5-728011b846cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Development'])[5]/following::a[5]</value>
      <webElementGuid>870f240e-098f-4473-bbb4-9e6703d869dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SensitivityLevel'])[1]/preceding::a[1]</value>
      <webElementGuid>0a91b5e6-f57d-4a1b-adc9-4eb7eb192199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VA_Iteration1_25'])[1]/preceding::a[1]</value>
      <webElementGuid>f91ec66b-e364-403d-bafc-7a9ea0b043ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/underwriting/rulebook/editRulebook!input.action?rulebookId=5442724')]</value>
      <webElementGuid>e07dcc33-db59-4ac6-bf7a-772fccccba65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[12]/a</value>
      <webElementGuid>629f13ce-bdef-4268-bdcb-5eaa1ade827a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/underwriting/rulebook/editRulebook!input.action?rulebookId=5442724' and (text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>220a6c10-c63e-44bc-b0d9-9f881bc0a358</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
