<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Amount Received</name>
   <tag></tag>
   <elementGuidId>c5d7ab9d-fb67-47dd-8fab-1cb01be37a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-Q_AmtCashWithApp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_AmtCashWithApp']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1726b541-332e-491a-b4f1-9ee896a2b964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05ee69a5-656d-4ad1-a5e1-dbbb2e6ad5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[6].answers[0].value</value>
      <webElementGuid>b3f072a0-c42e-47bb-b6b9-47d8164f0de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_AmtCashWithApp</value>
      <webElementGuid>f10532dd-2026-4402-b0c5-d656a942be01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>7b016018-56fc-43f9-b5ac-3c5cf48d799f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_AmtCashWithApp&quot;)</value>
      <webElementGuid>38a74b6e-8fc3-46de-8ae8-c7a5c4463432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_AmtCashWithApp']</value>
      <webElementGuid>4ca73e0d-40ba-4607-92ec-ecb132a0f49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_AmtCashWithApp']/div/div[2]/div/div/input</value>
      <webElementGuid>b75b6187-c182-4244-a92d-b17ee399ed98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/div/div/input</value>
      <webElementGuid>6a286dee-4b4c-4f18-bdd2-a7a9cec9e48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[6].answers[0].value' and @id = 'element-Q_AmtCashWithApp']</value>
      <webElementGuid>77a0706d-c732-4827-985d-2d2a147d44bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
