<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CB1 Address Line 2</name>
   <tag></tag>
   <elementGuidId>a9ae5a89-9791-4ce8-8dde-7216437ec566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-Q_CB_Address2_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_CB_Address2_1']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d85c370a-a919-494c-899e-9bae950a5c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c11df109-7720-42e8-930e-27e4e6fdf4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[29].answers[0].value</value>
      <webElementGuid>514312d5-110a-4e59-a627-7a2672704e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_CB_Address2_1</value>
      <webElementGuid>1f9a3548-3548-4cd7-9c55-8a96b73979e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>3e811621-71f5-4cf4-bb9d-c858c6941cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_CB_Address2_1&quot;)</value>
      <webElementGuid>e70a5a9d-93f2-4e4a-ba09-fd9d1df00d59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_CB_Address2_1']</value>
      <webElementGuid>ad2962fb-1f87-4083-be4d-2f6f79139c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_CB_Address2_1']/div/div[2]/div/div/input</value>
      <webElementGuid>6b86ed2e-f1c8-4d7a-8b9b-fe95c7acdd72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[11]/div/div/div[2]/div/div/input</value>
      <webElementGuid>a791f658-4914-4cd0-87aa-5ed1b3d399aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[29].answers[0].value' and @id = 'element-Q_CB_Address2_1']</value>
      <webElementGuid>8f8039c4-4560-4a65-9399-131659f5a33b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
