<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CB1 Address Line 1</name>
   <tag></tag>
   <elementGuidId>1da454ef-8a8d-48be-9d32-63d79d9bc72f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-Q_CB_Address_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_CB_Address_1']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51c61a24-0358-4a34-982a-4a46c4002513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>113d0f53-e6c9-4e0a-bcf9-d7f53039ce39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[28].answers[0].value</value>
      <webElementGuid>e902a64d-35ef-4a0f-8aa1-511e041fc417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_CB_Address_1</value>
      <webElementGuid>2f65e437-61fa-46ac-9b83-689cd1edcfab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>1c099a43-21f2-4986-9972-373302278fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_CB_Address_1&quot;)</value>
      <webElementGuid>63aaaba3-85f1-4594-8c8a-f145eda88ec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_CB_Address_1']</value>
      <webElementGuid>0a32f863-b35c-4a9b-a12d-e2434143d576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_CB_Address_1']/div/div[2]/div/div/input</value>
      <webElementGuid>c8a7ada8-b0d3-4cc1-aea2-8901c5f69519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[10]/div/div/div[2]/div/div/input</value>
      <webElementGuid>d78e8cfc-68a1-4322-8a51-48626375f256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[28].answers[0].value' and @id = 'element-Q_CB_Address_1']</value>
      <webElementGuid>1f79a452-10c1-46b5-ba76-0d1e38763d5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
