<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CB1 First Name</name>
   <tag></tag>
   <elementGuidId>1e8a544b-2f89-4bdf-bfcf-6199c5b4ede2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-Q_CB_Name_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_CB_Name_1']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>844eec9d-194f-451a-8432-a25700dc6595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6be8bc9b-e37d-49bc-b42a-840539e2bcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[21].answers[0].value</value>
      <webElementGuid>ac3a4364-66d5-4a45-ad22-ea002d7fbf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_CB_Name_1</value>
      <webElementGuid>15f6878e-089c-4dc1-93c4-82dabb1cb6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>e306046a-252d-4c5a-8b8b-43a2e88a947b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_CB_Name_1&quot;)</value>
      <webElementGuid>49b155ed-50b9-467b-b2db-9e5297b98b7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_CB_Name_1']</value>
      <webElementGuid>305f818f-9d6c-4fb5-a7ea-38141e5aa901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_CB_Name_1']/div/div[2]/div/div/input</value>
      <webElementGuid>63fed953-d662-4a09-82b4-50c3f57a978b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>5998f20c-e1e2-4181-a65b-68e5f70ae604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[21].answers[0].value' and @id = 'element-Q_CB_Name_1']</value>
      <webElementGuid>e41ca4af-4b0f-4fa2-96c0-2bd068c5d84a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
