<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Continue button</name>
   <tag></tag>
   <elementGuidId>149970f6-b687-4d1e-b392-4ebfde8899df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_nextPageContinue_execute</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1e042f96-78c3-4552-b794-9e31aea702c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fb8c3d76-e55c-4073-adf0-65c8b412671a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_nextPageContinue_execute</value>
      <webElementGuid>5cf9fbb7-6045-4ec3-a2c0-ca2e36d76fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:nextPageContinue!execute</value>
      <webElementGuid>0a09faf0-7fca-4004-a95a-07718443e841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue ></value>
      <webElementGuid>3ef26941-4647-4299-aa6d-e3f9e5a40068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary</value>
      <webElementGuid>cf57da88-d765-4ce8-a98d-23965c7d69d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_nextPageContinue_execute&quot;)</value>
      <webElementGuid>50f9daaa-bb06-4381-8c37-b29c14c6bdab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      <webElementGuid>25a26fc2-0c90-4dc6-99c6-23fb9b0fe909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-continue']/input</value>
      <webElementGuid>5e39fe72-a294-43bd-97be-e475141b5add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>e1244e31-4646-4944-bfcf-ef73c2421907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'el-content-form_nextPageContinue_execute' and @name = 'action:nextPageContinue!execute']</value>
      <webElementGuid>22dec3bd-b53f-40f7-8e6b-e94ea78e46ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
