<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PB1 Zip Code</name>
   <tag></tag>
   <elementGuidId>8ab61568-daf2-4d65-be6b-60a21d5133b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-Q_PB_Zip_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_PB_Zip_1']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2c2ce64-a843-46b8-94b1-d130711e37f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>55fccea7-ccc8-48ff-a500-9155b395ced8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[12].answers[0].value</value>
      <webElementGuid>b2ba2395-a3f0-4e6d-8012-e2595f91bfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_PB_Zip_1</value>
      <webElementGuid>e8560193-08b5-4bf0-8c0c-e814ae607a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control placeholderColor</value>
      <webElementGuid>902b4c40-47ef-45d4-8e84-138acf6673fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxxx</value>
      <webElementGuid>75b1fb9c-eaa6-4010-b6ae-ea783c3e1715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_PB_Zip_1&quot;)</value>
      <webElementGuid>d86ac270-877f-4fce-b69d-7ddd0013e849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_PB_Zip_1']</value>
      <webElementGuid>563725d0-b85f-46d2-a254-f437f181a630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_PB_Zip_1']/div/div[2]/div/div/input</value>
      <webElementGuid>94c64cd0-b198-44ea-b697-ebb9408c2c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/div/input</value>
      <webElementGuid>c874a72a-d918-4741-a2fa-681503177924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[12].answers[0].value' and @id = 'element-Q_PB_Zip_1' and @placeholder = 'xxxxx']</value>
      <webElementGuid>57a58c6c-d39f-4c35-8552-c825bdd706d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
