<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PB1 Address Line 2</name>
   <tag></tag>
   <elementGuidId>a917b728-4df0-47e2-ae51-d05e5ac96b04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#element-Q_PB_Address2_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_PB_Address2_1']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1793c5a-a37a-489b-93dc-1c2a74681dda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21025cc5-1c0d-4673-ac67-269a89356870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[9].answers[0].value</value>
      <webElementGuid>72455956-4a5d-44e7-ad4b-0a3587c0a521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_PB_Address2_1</value>
      <webElementGuid>ac3fb28a-6fe7-4a02-a082-5a13c8e2412b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>a00a2c01-505e-48d6-8578-aef014437a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_PB_Address2_1&quot;)</value>
      <webElementGuid>469e51db-8dcd-4b8d-8354-c2ea63ce98f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_PB_Address2_1']</value>
      <webElementGuid>0ac4996a-9615-4da8-beb8-efc47f22348c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_PB_Address2_1']/div/div[2]/div/div/input</value>
      <webElementGuid>22075c7e-bead-439c-aafa-7eb7fffa6976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[2]/div/div/input</value>
      <webElementGuid>08bc69f9-7953-4c05-bdf3-462d78cf9fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[9].answers[0].value' and @id = 'element-Q_PB_Address2_1']</value>
      <webElementGuid>c8acfb99-b0e1-4eaa-9f42-5f8135db551b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
