<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SDVI</name>
   <tag></tag>
   <elementGuidId>b2c3c6dc-b7e2-4ddc-b772-d7ae76ac8935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='score']/tbody/tr[7]/td[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>67fdf3ea-536f-47b0-a2dc-041e9558cd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SDVI</value>
      <webElementGuid>e1a60c69-bdf9-4c7f-8ff4-61e1c08668f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;score&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[4]</value>
      <webElementGuid>3ee7fef1-3ac1-46a4-a9a3-1f0f82603139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='score']/tbody/tr[7]/td[4]</value>
      <webElementGuid>8cff07a4-ee4e-4b13-89a6-80e3b52d464b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='root.SG_INPUT3'])[1]/following::td[2]</value>
      <webElementGuid>f448a3e5-727f-4261-ae47-1ac85d0274c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SG_INPUT3'])[1]/following::td[3]</value>
      <webElementGuid>17d60b58-e42e-4a6c-9c8c-ce41d6986eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SG_INPUT5'])[1]/preceding::td[1]</value>
      <webElementGuid>2d239d0f-8fba-4a31-9107-2cf835f94197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='root.SG_INPUT5'])[1]/preceding::td[2]</value>
      <webElementGuid>54881514-4065-4f47-9e7a-75b26d0928e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SDVI']/parent::*</value>
      <webElementGuid>5bd5c289-0f0a-4930-8306-a8528bbda380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]</value>
      <webElementGuid>2ed041da-9b06-430b-93af-53b30fdd7d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'SDVI' or . = 'SDVI')]</value>
      <webElementGuid>84a0cfbb-94b0-4fb0-ac1b-c1bec2a5c95d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
