<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GetWorkitemID</name>
   <tag></tag>
   <elementGuidId>09c35ab0-35b7-4f0a-9c21-d4a35cfb7e8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[contains(text(),'existing SDVI/VALI with same SSN')]//following::td[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startInterview_interview_readOnlyScores_0__totalString</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73758942-437f-4829-8f7e-790bb28d76c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b801c6df-cae1-427d-82ee-75114e10ee1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interview.readOnlyScores[0].totalString</value>
      <webElementGuid>ebbdaf58-acfd-4dd7-9f08-aa7a921e1531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startInterview_interview_readOnlyScores_0__totalString</value>
      <webElementGuid>70540acd-4137-4a5d-8ac1-b24201a22158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startInterview_interview_readOnlyScores_0__totalString&quot;)</value>
      <webElementGuid>62b0ab18-9608-46d7-8406-2f28f5380360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startInterview_interview_readOnlyScores_0__totalString']</value>
      <webElementGuid>1203f3f3-7179-4ba3-ad7c-cef5c1a4a563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='score']/tbody/tr/td[3]/input</value>
      <webElementGuid>7aa4b18d-50fa-47ba-948b-a7d4f6ac7890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>50abf3a3-df39-4040-843b-d7218ce7203e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'interview.readOnlyScores[0].totalString' and @id = 'startInterview_interview_readOnlyScores_0__totalString']</value>
      <webElementGuid>4962b7ae-4409-41ff-b8d5-ac668eb90a84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
