<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter Application Information</name>
   <tag></tag>
   <elementGuidId>54625b6e-b283-47ae-9d0c-4cd5a210b818</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metadataKeyNoDisplayWidth496 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Enter Application Information')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ff2a49f1-ca6b-403f-8d79-a75cc8b32b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>0dee6ef8-c9fb-4166-8db3-6ee8a73ea405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://ec04-vc02-web01:9303/equotes/nextPage!input.action?interviewId=495515&amp;interviewToken=7fcsz4DAcPqMQz67fU0F</value>
      <webElementGuid>fea57c79-56d4-4042-a96a-ca6746312e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter Application Information</value>
      <webElementGuid>5ff5629a-6b65-495c-b1a8-3bb289d28691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metadataKeyNoDisplayWidth496&quot;)/a[1]</value>
      <webElementGuid>041b42b7-34c6-44e8-b5c7-0c69e1c00fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metadataKeyNoDisplayWidth496']/a</value>
      <webElementGuid>a62d5e35-151e-4667-9df0-3b51150d6b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter Application Information')]</value>
      <webElementGuid>042f1110-75ad-4396-9d89-c9dc67b63bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name Does Not Match'])[1]/following::a[1]</value>
      <webElementGuid>bf60a4c8-e4ac-44fa-b9ad-bce2c4ff7e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/following::a[1]</value>
      <webElementGuid>03ecec1a-3910-47e5-9dcf-65b0909a3c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open eApp'])[1]/preceding::a[1]</value>
      <webElementGuid>8be5bf25-ee40-40b9-bded-f47af62e729f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to VCE'])[1]/preceding::a[1]</value>
      <webElementGuid>aa34efeb-19ad-4512-b618-9cddddc64ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Application Information']/parent::*</value>
      <webElementGuid>bd450aac-fdfa-4c1e-b207-a3c5f1ced660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://ec04-vc02-web01:9303/equotes/nextPage!input.action?interviewId=495515&amp;interviewToken=7fcsz4DAcPqMQz67fU0F']</value>
      <webElementGuid>28f49868-ec6f-4366-b882-650117f75504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/a</value>
      <webElementGuid>276b767b-1cc6-4455-bf3b-0fa90e26f32f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://ec04-vc02-web01:9303/equotes/nextPage!input.action?interviewId=495515&amp;interviewToken=7fcsz4DAcPqMQz67fU0F' and (text() = 'Enter Application Information' or . = 'Enter Application Information')]</value>
      <webElementGuid>9ba307bb-8232-471e-b4b0-46d8846bb2a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
