<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address3</name>
   <tag></tag>
   <elementGuidId>a8bb8316-63cb-4f94-a230-1d254d2f2ab5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_23__value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_23__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35728d03-97f0-4159-838b-1bb470ffb803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f868c26c-c8ee-4369-9f86-02a32d662c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[23].value</value>
      <webElementGuid>4391a897-6b5e-40d5-8d21-130944a3241b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_23__value</value>
      <webElementGuid>231d89b8-7e7d-4cba-aabc-b236acb0abff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>cdd3ff2c-c2e6-4ad7-9c56-0119b6eebb1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;693&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>8cbc31b2-2de1-471a-bc78-679af5c0dd9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_23__value&quot;)</value>
      <webElementGuid>a365ae6b-b8df-41ea-b93c-7ffd5032ef91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_23__value']</value>
      <webElementGuid>a2f2a976-a68f-464a-a9d1-af65e578324b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_23__value']/input</value>
      <webElementGuid>3a6720fc-3507-491a-b277-21caf845bae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/div/div/div/div/input</value>
      <webElementGuid>437cb190-7d5c-4b77-b7ea-a5c0629df78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[23].value' and @id = 'workflowDetails_input_itemMetadata_23__value']</value>
      <webElementGuid>71509eb8-9ae1-4631-90ef-7d98c2a17055</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
