<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Open eApp</name>
   <tag></tag>
   <elementGuidId>f9ccf3a0-571d-4013-9f06-8a43fb6cb1ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#metadataKeyNoDisplayWidth488 > button[type=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c9e4d50-ae7f-4d85-91e1-6321f7dbf4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59f32107-209f-42f9-abc8-a2cbec83eb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cssclass</name>
      <type>Main</type>
      <value>el-button ui-state-default ui-corner-all left</value>
      <webElementGuid>e76564b6-306f-476d-b8fd-51da94bad04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>callButtonAction(event,488);</value>
      <webElementGuid>1b750861-8c71-438a-bd8e-66953bdab27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open eApp</value>
      <webElementGuid>80083615-658f-4d33-bd41-29bdaa50c4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metadataKeyNoDisplayWidth488&quot;)/button[1]</value>
      <webElementGuid>1b4f5fdd-a05d-4ec6-b497-058d375e511e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>c9641074-0609-47b3-a0c3-8481171423ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metadataKeyNoDisplayWidth488']/button</value>
      <webElementGuid>40c61df0-17b1-4b05-95fb-fc60c72db8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name Does Not Match'])[1]/following::button[1]</value>
      <webElementGuid>502ae3db-0a77-4dd7-8a5e-0add0b6c86fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/following::button[1]</value>
      <webElementGuid>4214d287-54d1-4c4a-b06d-5176ac5c9f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to VCE'])[1]/preceding::button[1]</value>
      <webElementGuid>6d595997-61af-4e1b-b5d9-45b6b2958cec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open eApp'])[2]/preceding::button[2]</value>
      <webElementGuid>1829b330-b8e4-4fca-80e3-fb6a23f7a381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open eApp']/parent::*</value>
      <webElementGuid>e4b5c5ba-23f3-441c-8f6c-fd4f7372816e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[39]/td[2]/div/div/button</value>
      <webElementGuid>6949f67b-39c8-4dfd-b221-b21315ed8c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Open eApp' or . = 'Open eApp')]</value>
      <webElementGuid>db8c1924-7177-42e6-b845-c86fc6ceff3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
