<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Claim Number_itemMetadata12.value</name>
   <tag></tag>
   <elementGuidId>2e24ede8-656c-4be2-aa0d-988d4011dff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_12__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;metadataKeyNoDisplayWidth464&quot;]//following::input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ce718d1-8d64-4a1a-a460-70e8d67c41d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f1be1908-d96a-4367-8a07-3351520e67af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[12].value</value>
      <webElementGuid>48153cb0-5b6f-41f2-879f-3e853e47b65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_12__value</value>
      <webElementGuid>ec7f805e-2b7a-450b-b4fd-1ac336a44be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>c0698fe3-2165-423f-9f10-d3aa03bca7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;464&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>02962f08-1df2-410f-a699-0993ec31d68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_12__value&quot;)</value>
      <webElementGuid>bade5305-7490-43f8-8f5d-8a82e2012b5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_12__value']</value>
      <webElementGuid>01e1fc76-f05c-4a4b-9d00-0aa17d4e7740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_12__value']/input</value>
      <webElementGuid>38cafa5d-cb77-4079-9bc1-e1ba50e4b950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/div/div/div/input</value>
      <webElementGuid>6308489c-0a0c-4ac2-89fc-f5c320536d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[12].value' and @id = 'workflowDetails_input_itemMetadata_12__value']</value>
      <webElementGuid>bc8c0f52-327b-42a4-8c9e-627b9d6bd3fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
