<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_itemMetadata27.value</name>
   <tag></tag>
   <elementGuidId>e4a2b533-a564-4854-bc3b-a13346396821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_27__value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_27__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9753aecd-a66b-410e-b304-2f159b19d442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c3248e7-ac90-4701-b724-9b5c7af80605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[27].value</value>
      <webElementGuid>a9d43708-b281-4e47-9705-ad4bfe116659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_27__value</value>
      <webElementGuid>d5750fca-4fac-4fc1-8fd9-fc248ae2bba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>9def50f9-90b5-44d7-aa26-1a8976acc4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;482&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>4a436d4a-3567-4660-8d32-f7dfd9edc365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>44729bcf-9dc1-4e32-ad0c-38548a90f842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_27__value&quot;)</value>
      <webElementGuid>6c6046c8-d84f-417c-bb6e-3d1b6d8dd30b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_27__value']</value>
      <webElementGuid>6a70ea5e-21ea-4a61-96e9-fba08715e99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_27__value']/input</value>
      <webElementGuid>4d635285-2c58-4d31-9f59-8aa9e1eee48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[2]/div/div/div/div/input</value>
      <webElementGuid>130d1393-df57-44fc-b446-4fa856b074ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[27].value' and @id = 'workflowDetails_input_itemMetadata_27__value']</value>
      <webElementGuid>28a59878-c869-4eac-b7c6-926edbc7e704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
