<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_itemMetadata24.value</name>
   <tag></tag>
   <elementGuidId>9ab66649-2b0a-4c2f-8288-e04ba7651f99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_24__value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_24__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5aafaa93-b669-4140-889c-48d2068443ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf510824-b4b9-4f05-a705-81216beec2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[24].value</value>
      <webElementGuid>c08fd06d-99a8-4d3c-83c1-5a4f392f722c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_24__value</value>
      <webElementGuid>d778a94c-2107-4a4a-a2fc-c66e0a6da23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>cfccd80f-3604-42ea-bfe5-4b82788f207e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;480&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>ade9fa96-81eb-4a3a-801c-64155d1b413f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_24__value&quot;)</value>
      <webElementGuid>ae06b9cc-a808-4670-91eb-8e60e6002e37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_24__value']</value>
      <webElementGuid>162a64e5-bb22-4a5d-be34-17d0d3ce71a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_24__value']/input</value>
      <webElementGuid>cf377a44-10fb-49e4-8c21-d4390cc0da56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/div/div/div/div/input</value>
      <webElementGuid>3bba5fdf-038e-4000-833d-1751bde63f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[24].value' and @id = 'workflowDetails_input_itemMetadata_24__value']</value>
      <webElementGuid>01a031f4-c515-429d-a3a6-3cb30006281b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
