<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Additional References_actionwo_9eb6ef</name>
   <tag></tag>
   <elementGuidId>535eafc6-2aaa-4da0-8a90-658b8b0bd240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quickActionsForm_workflowSearch_submit_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#quickActionsForm_workflowSearch_submit_search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b136d7ca-85bb-49ae-af58-a1525f5308f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>09a9db58-7f13-4184-99b1-f381407ed148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>ac1a04af-4cfb-44d4-8e19-4429b3399377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quickActionsForm_workflowSearch_submit_search</value>
      <webElementGuid>5dfe9d87-bbd3-4fac-ac3d-5aa9dbc35cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:workflowSearch!search</value>
      <webElementGuid>a9004aef-4b38-4ad3-975e-9b700815677a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right el-button ui-state-default ui-corner-all ui-button ui-widget ui-state-hover ui-state-focus</value>
      <webElementGuid>ca00daac-20ab-4a1e-a6b3-31556ba159e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>838fa1ae-b83c-46b9-b7ac-f19c475d2284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>03665f5e-d219-4eeb-a349-25a670028914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quickActionsForm_workflowSearch_submit_search&quot;)</value>
      <webElementGuid>4720cf75-b7f4-4a3a-bd13-256a9058ea88</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quickActionsForm_workflowSearch_submit_search']</value>
      <webElementGuid>d896266e-0c58-4df6-b52a-c42671109ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_quickActionsForm_workflowSearch_submit_search']/input</value>
      <webElementGuid>10f86f97-fad9-4772-861f-18e113e312d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>3372c049-2284-47b3-b8f9-d86bae012f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'quickActionsForm_workflowSearch_submit_search' and @name = 'action:workflowSearch!search']</value>
      <webElementGuid>1c43f0e6-6f0a-498a-b641-163dfc02a878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
