<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_LISSIAflow</name>
   <tag></tag>
   <elementGuidId>b73555bc-0961-42c4-9374-b7455ea577fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dashboard-seperator&quot;]/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.el-button.ui-state-default.ui-corner-all.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c4adeb64-a709-4169-b76c-b7459c7e1951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/workflow/</value>
      <webElementGuid>b78a05af-a7f0-4638-83b9-5a69a7901192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>dc0e9899-2caf-4266-8bf9-d22da9418075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LISSIAflow</value>
      <webElementGuid>23829851-bda1-468d-ab87-b85b7ef81d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-seperator&quot;)/ul[1]/li[1]/a[@class=&quot;el-button ui-state-default ui-corner-all ui-state-hover&quot;]</value>
      <webElementGuid>4922ea35-1a14-4e64-977c-0e4ccf7aa33e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-seperator']/ul/li/a</value>
      <webElementGuid>83e97de6-bba4-454b-b6a8-ab114aa80049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LISSIAflow')]</value>
      <webElementGuid>e25144f9-8f16-4892-8bbe-f4b3a2fdf730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you wish to confirm?'])[1]/following::a[2]</value>
      <webElementGuid>fdef5eb2-e3a5-4efa-9208-9614419a57b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm!'])[1]/following::a[2]</value>
      <webElementGuid>a95381da-e2f5-4d61-9f85-f9881ac70d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='uLISSIA'])[1]/preceding::a[1]</value>
      <webElementGuid>fb5521d4-a5d1-4c73-aa5e-11b7e8d3d8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LISSIADashboard'])[1]/preceding::a[2]</value>
      <webElementGuid>944b502a-e982-413d-a83f-a741845ab7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LISSIAflow']/parent::*</value>
      <webElementGuid>a61884df-8fdb-4a12-8ab9-abf26c1b0e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/workflow/')]</value>
      <webElementGuid>316c8f7d-3edb-4b99-be70-2a9e0afba471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>63beca78-c1a9-4a14-9f5d-6d9ce913fca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/workflow/' and (text() = 'LISSIAflow' or . = 'LISSIAflow')]</value>
      <webElementGuid>1e29e817-8300-4f79-9526-9520523d8165</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
