<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --    AA    AE    A_2f9a67</name>
   <tag></tag>
   <elementGuidId>3ef4efd7-7e18-4bdb-a61b-749564982abb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='workflowDetails_input_itemMetadata_25__value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_25__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>edb14240-877e-4b21-859e-a0bf5fbd971a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[25].value</value>
      <webElementGuid>4cbbdc57-e141-40b5-a80e-bc2abb893648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_25__value</value>
      <webElementGuid>27339f37-12e2-4bbb-a759-b7c01a9e2529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>1111b1a5-3153-4771-9e5f-d279a4758d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;481&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>0e3033e4-ebe2-4ee6-a379-0e7db3a2e81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bs-select-hidden</value>
      <webElementGuid>7e531fc2-3af6-40e7-8715-7a5cebea77f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    -- Please Select --
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


</value>
      <webElementGuid>2339c587-2ca9-4408-a957-3b039fdca8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_25__value&quot;)</value>
      <webElementGuid>2cc7eb2b-01c2-47d7-a040-fa1395588134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='workflowDetails_input_itemMetadata_25__value']</value>
      <webElementGuid>d35b54fd-7645-4c18-a1d2-d60f839a96e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_25__value']/select</value>
      <webElementGuid>57392dbf-f735-45c4-be67-397fd3fb5669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[1]</value>
      <webElementGuid>30e8a7f2-fcf0-4b34-a18f-80adaca0b64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>e1ebee0c-66fd-4b4e-af0d-f78e87e8eba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Please Select --'])[4]/preceding::select[1]</value>
      <webElementGuid>aadce28d-a0f2-451a-9823-930ee540f29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Please Select --'])[5]/preceding::select[1]</value>
      <webElementGuid>bc3c7d92-38ba-486d-a195-39f570f30cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[2]/div/div/div/div/select</value>
      <webElementGuid>10b6b103-3613-4dd6-bc6d-0d87741b589b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'itemMetadata[25].value' and @id = 'workflowDetails_input_itemMetadata_25__value' and (text() = '
    -- Please Select --
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


' or . = '
    -- Please Select --
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


')]</value>
      <webElementGuid>839ffb31-2d3b-429c-a9d6-0d18b606dce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
