<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Enter Application Information</name>
   <tag></tag>
   <elementGuidId>ceef1e21-fc9b-4efe-9da6-0230d9eb83f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metadataKeyNoDisplayWidth496 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Enter Application Information')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>756916bb-831c-491c-949c-f123205eb6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>3eb85e89-750b-4285-b154-e68bda0fab8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://ec04-vc02-web01:9303/equotes/nextPage!input.action?interviewId=495515&amp;interviewToken=7fcsz4DAcPqMQz67fU0F</value>
      <webElementGuid>fdb0e5a9-31f3-45f1-9c15-d48c4e5ae6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter Application Information</value>
      <webElementGuid>8349c1bb-fff2-4e03-9dde-fe0d8ea49cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metadataKeyNoDisplayWidth496&quot;)/a[1]</value>
      <webElementGuid>ed896400-1746-4f60-a4c3-4341a4656fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metadataKeyNoDisplayWidth496']/a</value>
      <webElementGuid>f71596b9-b7cb-4742-8cf8-406af8f98d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Enter Application Information')]</value>
      <webElementGuid>1fa4375c-aba8-4676-bb72-ada8b453e5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name Does Not Match'])[1]/following::a[1]</value>
      <webElementGuid>327a224c-b7f4-4484-90cd-806aba7051be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/following::a[1]</value>
      <webElementGuid>a5657f09-ad16-4dbc-93f6-9a3cac900d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open eApp'])[1]/preceding::a[1]</value>
      <webElementGuid>fc11438a-4926-4804-9c82-5238a4659da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to VCE'])[1]/preceding::a[1]</value>
      <webElementGuid>d5dd174d-7687-4974-9686-e13ffe6cc29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Enter Application Information']/parent::*</value>
      <webElementGuid>38ed29f1-1bb2-4879-90de-b02e8e91d59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://ec04-vc02-web01:9303/equotes/nextPage!input.action?interviewId=495515&amp;interviewToken=7fcsz4DAcPqMQz67fU0F']</value>
      <webElementGuid>d5dad2f8-c568-4c01-9861-98a0dd3b4673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/a</value>
      <webElementGuid>91ac126f-bafd-410e-b40a-08a48e0175f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://ec04-vc02-web01:9303/equotes/nextPage!input.action?interviewId=495515&amp;interviewToken=7fcsz4DAcPqMQz67fU0F' and (text() = 'Enter Application Information' or . = 'Enter Application Information')]</value>
      <webElementGuid>ba5aa476-4a9b-4a23-b78f-3e795e35a6fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
