<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address1</name>
   <tag></tag>
   <elementGuidId>785e8876-48a1-4bbc-a801-b0e75f58f7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_21__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_21__value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e3878e2-e935-4214-a26f-95789f2fd718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9a07ca89-e2d7-4744-964a-670e6d6a1eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[21].value</value>
      <webElementGuid>0628b3d7-b076-450a-81ab-f301ae99a7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_21__value</value>
      <webElementGuid>52a9ae5b-a3e0-40ce-b68f-faeaceef9ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>542cb45d-9972-473e-84a0-a5d57683cfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;469&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>250adf7d-038e-49bd-85c2-b7cca0a8e5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_21__value&quot;)</value>
      <webElementGuid>e220ab1b-4687-4de1-9f83-2a85b71eae65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_21__value']</value>
      <webElementGuid>b960fd1d-ff41-45c3-ab24-1d1da6e78e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_21__value']/input</value>
      <webElementGuid>5d99a6e0-44a0-4ada-ae3c-dca49f9052a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[2]/div/div/div/div/input</value>
      <webElementGuid>afdf1bac-d9e7-4c34-8d60-032c700f9479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[21].value' and @id = 'workflowDetails_input_itemMetadata_21__value']</value>
      <webElementGuid>af500c33-b3ec-401d-9854-00f4440ee37c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
