<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address3</name>
   <tag></tag>
   <elementGuidId>620123f1-6fd8-4b40-8b2b-1f3bbe87e940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_23__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_23__value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5088a103-5b7d-44bb-acdd-70bf495fe5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>076e7360-e05d-41ad-8ce5-f523a8d4a08e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[23].value</value>
      <webElementGuid>d0119e9b-0edf-4b2e-bdc6-2636595152e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_23__value</value>
      <webElementGuid>7a25ec44-c373-4396-be82-fa908744db7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>f556c9b0-95a3-4566-a493-a9f5677ba1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;693&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>adee196f-ec6c-46a2-866c-e08c52b2ab20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_23__value&quot;)</value>
      <webElementGuid>455fbc56-574b-4d8c-aec5-398c244bb001</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_23__value']</value>
      <webElementGuid>a46d7a5f-a8e7-4317-b1b9-9f46a7bd7b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_23__value']/input</value>
      <webElementGuid>2a0cefec-07db-4310-8a72-7268e5d50fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[18]/td[2]/div/div/div/div/input</value>
      <webElementGuid>3f422c46-0955-47a1-bde5-b3cfb901721b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[23].value' and @id = 'workflowDetails_input_itemMetadata_23__value']</value>
      <webElementGuid>ce77775c-d769-42b4-83ee-45a218fe3a9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
