<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Open eApp</name>
   <tag></tag>
   <elementGuidId>aedcbf1a-38b7-4c11-b9ff-3452daf36697</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#metadataKeyNoDisplayWidth488 > button[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02464866-9fd1-4c5e-b8ab-d8fd3bb3083b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e5b78a0-f236-4a2c-9265-0f953ed38d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cssclass</name>
      <type>Main</type>
      <value>el-button ui-state-default ui-corner-all left</value>
      <webElementGuid>feb81882-d014-4cdf-9472-17ec4408f58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>callButtonAction(event,488);</value>
      <webElementGuid>c896fa12-3aff-48a5-b03d-551dcfee6990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Open eApp</value>
      <webElementGuid>4932cd6d-05cc-4396-99ee-0f85ae135f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;metadataKeyNoDisplayWidth488&quot;)/button[1]</value>
      <webElementGuid>c8ae3edb-e99a-4118-b3bb-0099db768748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>78387fb6-940f-4561-8a95-a5f8d69bbb61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='metadataKeyNoDisplayWidth488']/button</value>
      <webElementGuid>1e8fc173-e59a-4a4a-a88f-d014561f3762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name Does Not Match'])[1]/following::button[1]</value>
      <webElementGuid>c45b7f36-1dde-4548-a38a-8c4cf32a0753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[4]/following::button[1]</value>
      <webElementGuid>482906b4-9939-4c9e-a0fa-ee4f1144bdcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send to VCE'])[1]/preceding::button[1]</value>
      <webElementGuid>93288b32-22c0-4443-bb14-8415dfb24d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open eApp'])[2]/preceding::button[2]</value>
      <webElementGuid>87b8acaf-0169-4423-a2aa-5dad93f3763c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Open eApp']/parent::*</value>
      <webElementGuid>4a522a40-6bd7-4ba0-8859-10477fce5ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[39]/td[2]/div/div/button</value>
      <webElementGuid>2472e306-316d-4160-a267-7240b073802b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Open eApp' or . = 'Open eApp')]</value>
      <webElementGuid>acecef57-ac71-4996-b42d-89d81955ab21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
