<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Claim Number</name>
   <tag></tag>
   <elementGuidId>82eb279d-3b5c-4e45-9aee-19beb6a60c0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_12__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;workflowDetails_input_itemMetadata_14__value&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5fa93a8-447c-4f4b-9023-c03fba6d8a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>42e41975-d53d-4810-aac8-a091a9aa0126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[12].value</value>
      <webElementGuid>7c93ca61-7a11-42f3-a7e5-05487254a24b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_12__value</value>
      <webElementGuid>81f8cd85-6342-487c-a515-ecb66a5f2a36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>f31ce513-1462-4c51-bdfa-80df4f84b2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;464&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>173776f5-c9fb-4cc6-aa0b-b591219a14e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_12__value&quot;)</value>
      <webElementGuid>204e81e1-0bcd-452b-8afb-abdca03db7fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_12__value']</value>
      <webElementGuid>fe78ac90-4474-4bf4-a7e3-8566eb0597b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_12__value']/input</value>
      <webElementGuid>9630401a-5d8f-443f-baee-c0e35565c37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/div/div/div/input</value>
      <webElementGuid>7b6606b7-4842-4550-887f-6af3dcb579ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[12].value' and @id = 'workflowDetails_input_itemMetadata_12__value']</value>
      <webElementGuid>134196da-f058-404d-b885-02917f30c5e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
