<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_itemMetadata24.value</name>
   <tag></tag>
   <elementGuidId>d3674ed1-bca5-47cd-aebc-a667e8fc06b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_24__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_24__value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dcfa5316-cb38-4fc5-a938-f61434fdc9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e987115c-35c4-4365-9184-bc4a56914db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[24].value</value>
      <webElementGuid>67f691da-8159-4b03-96ee-7974b833c39e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_24__value</value>
      <webElementGuid>de6b2ced-9bc1-4c0a-9bef-1097c66956b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>686cc127-275c-47f4-a7cf-d87d2113e3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;480&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>7dedc897-5a73-404a-95e3-89791d84a775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_24__value&quot;)</value>
      <webElementGuid>4a914134-1d79-4182-b019-0df761ccc937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_24__value']</value>
      <webElementGuid>6327ac21-b089-44e2-9a89-53f4d5b1a2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_24__value']/input</value>
      <webElementGuid>f1c38ec2-0050-4d75-ba1f-fa6246c319f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[2]/div/div/div/div/input</value>
      <webElementGuid>2dda41ac-f9b3-4e42-b8fe-6658330d8cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[24].value' and @id = 'workflowDetails_input_itemMetadata_24__value']</value>
      <webElementGuid>f0bde21e-a0c4-4217-a517-695d898501dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
