<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Additional References_actionwo_9eb6ef</name>
   <tag></tag>
   <elementGuidId>ea6714e0-781b-486c-8fc8-1d601671eca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quickActionsForm_workflowSearch_submit_search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quickActionsForm_workflowSearch_submit_search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5a3d2634-fa98-4ffb-9e18-0d0585092bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3807ede3-8148-4b58-affe-3ce5d2c48e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>0017b10c-f978-4828-a4bc-6ed5d85f7030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quickActionsForm_workflowSearch_submit_search</value>
      <webElementGuid>ef0b6bb2-1cfe-48bf-82a8-606270daca68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:workflowSearch!search</value>
      <webElementGuid>f7a2624a-b29e-430e-89d5-eff4d6e16454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right el-button ui-state-default ui-corner-all ui-button ui-widget ui-state-hover ui-state-focus</value>
      <webElementGuid>e56db4c8-7296-4b7b-a5db-a5ad98a51fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e6fae0b-1c7c-4095-8548-ff3cda7075df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9e67a051-06a0-414d-ac84-91e34544bd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quickActionsForm_workflowSearch_submit_search&quot;)</value>
      <webElementGuid>5241b512-9419-4043-8058-e6278d3f6854</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quickActionsForm_workflowSearch_submit_search']</value>
      <webElementGuid>79b6b085-9ea0-4866-9c0f-2995e5d037ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_quickActionsForm_workflowSearch_submit_search']/input</value>
      <webElementGuid>99bdb625-08df-43a3-9770-24d33ddc6353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>2c77e09f-073b-4983-8e2b-1706f3a6405e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'quickActionsForm_workflowSearch_submit_search' and @name = 'action:workflowSearch!search']</value>
      <webElementGuid>4526aeea-4468-4a85-81aa-1d1e3672492d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
