<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_itemMetadata28.value</name>
   <tag></tag>
   <elementGuidId>a42c7478-9f29-4ebb-9840-38eeeb2ff531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_28__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_28__value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92c5fd5a-68c4-4a87-9249-a563125a6420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4dabad72-4274-4f6d-834e-67616c5ec282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[28].value</value>
      <webElementGuid>9134a40c-6f5f-487a-8822-a76096197e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_28__value</value>
      <webElementGuid>3235a146-ee46-45a5-9074-ae58bfcbad8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>2bf37938-446b-4984-9d64-8f46236d1055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;532&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>f3f760c6-00a1-4b93-a40b-6a4f59f23377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>b63602a2-226a-4748-b40c-86448bac5406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_28__value&quot;)</value>
      <webElementGuid>5256d5b5-36fc-4a6d-a478-f614206b0715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_28__value']</value>
      <webElementGuid>779fcf06-6479-4191-8c38-81e3eba45ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_28__value']/input</value>
      <webElementGuid>91924d3f-df3f-44ea-96d7-7f065217a710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td[2]/div/div/div/div/input</value>
      <webElementGuid>574279e8-4ff2-458c-b272-5a152ce5719c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[28].value' and @id = 'workflowDetails_input_itemMetadata_28__value']</value>
      <webElementGuid>fa9e35fe-c653-470b-a120-612a828ea7f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
