<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Claim Number_itemMetadata12.value</name>
   <tag></tag>
   <elementGuidId>9ce833fb-7d7d-4b13-8353-c6fde4ade29d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_12__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;metadataKeyNoDisplayWidth464&quot;]//following::input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de905800-70e3-4705-9f62-0a1a9f89e1ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>556551ec-f1a1-4ef1-9bb4-5a5007664163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[12].value</value>
      <webElementGuid>524c007e-29ce-494a-b4a3-29f9a7edc1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_12__value</value>
      <webElementGuid>6fe79f18-b597-4462-8865-86e3dc4fd1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>0b2e412b-d8ab-46fe-931b-b346a796341a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;464&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>c2fe7a2c-0ee0-402f-82d8-b7fdc483da6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_12__value&quot;)</value>
      <webElementGuid>a853e715-182c-4a1a-be8e-52b790dff67a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_12__value']</value>
      <webElementGuid>e24b9cf3-d203-474c-9975-38dbb0597067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_12__value']/input</value>
      <webElementGuid>13addb37-66cb-4f45-b985-500c09ad5b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/div/div/div/div/input</value>
      <webElementGuid>d4bdba31-ed07-446b-a7d9-8685e255f5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[12].value' and @id = 'workflowDetails_input_itemMetadata_12__value']</value>
      <webElementGuid>80082c64-800c-40f0-b2b0-b425f98b6d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
