<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MMDDYYYY_itemMetadata30.value</name>
   <tag></tag>
   <elementGuidId>f0ab3436-9bb0-4130-a03c-68f77df74580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_30__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowDetails_input_itemMetadata_30__value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e16afd3-f4b4-4aca-9edb-e8e7a5edd26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89bf116e-71ae-4848-a96e-3897c0512455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[30].value</value>
      <webElementGuid>6e52a3e9-d4da-4ebe-b3f9-d1f9fd6905f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_30__value</value>
      <webElementGuid>7dc1ab5b-efda-49b9-8e37-3a8c82549542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker hasDatepicker</value>
      <webElementGuid>f51a6bd3-e2c9-4509-9b83-900ef6012dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>49815173-a4b0-42fd-983b-5bc777cd85ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;4164&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>c5270cf5-0efc-47eb-9a87-4e971effbeac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_30__value&quot;)</value>
      <webElementGuid>8791fac6-5d02-45bc-8438-273bb6a83c83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowDetails_input_itemMetadata_30__value']</value>
      <webElementGuid>8db8bf0a-5d22-4d9a-a06a-8d872c03d10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_30__value']/input</value>
      <webElementGuid>70bdd86e-ca58-4892-b6c1-26471fd46051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td[2]/div/div/div/div/input</value>
      <webElementGuid>055bd560-aa38-4fd8-9579-26a1f0f8efd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'itemMetadata[30].value' and @id = 'workflowDetails_input_itemMetadata_30__value']</value>
      <webElementGuid>541e6b19-12bc-4ccb-868d-eb038fd0b485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
