<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Link_LISSIAflow</name>
   <tag></tag>
   <elementGuidId>9d0a1da7-0d47-4314-89f4-35317d27ca0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.el-button.ui-state-default.ui-corner-all.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dashboard-seperator&quot;]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92a89c13-49b4-447d-b8e3-06fd98c42fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/workflow/</value>
      <webElementGuid>6514e1ad-a048-4476-8bf7-7af245578096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button ui-state-default ui-corner-all ui-state-hover</value>
      <webElementGuid>ac4c6535-0d39-453a-b1ac-cad0db0326a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LISSIAflow</value>
      <webElementGuid>a2dabbf8-517f-49eb-9b2b-02d0abbd00e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard-seperator&quot;)/ul[1]/li[1]/a[@class=&quot;el-button ui-state-default ui-corner-all ui-state-hover&quot;]</value>
      <webElementGuid>3b1ce011-23f7-4a98-8383-aea2b4a059d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dashboard-seperator']/ul/li/a</value>
      <webElementGuid>1ab2766a-786a-4c9a-a027-5fec8b20ebba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LISSIAflow')]</value>
      <webElementGuid>66112ede-f443-4407-b687-decb062988c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you wish to confirm?'])[1]/following::a[2]</value>
      <webElementGuid>93ce5c7c-3958-495a-be03-f6d340c0bac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm!'])[1]/following::a[2]</value>
      <webElementGuid>f8ca4d6e-0f69-4943-a61b-40c9b9632dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='uLISSIA'])[1]/preceding::a[1]</value>
      <webElementGuid>d66ccb4e-8526-416b-840b-bb8ecf059714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LISSIADashboard'])[1]/preceding::a[2]</value>
      <webElementGuid>8db6eaea-b6e1-425a-a45b-ab02141d0be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LISSIAflow']/parent::*</value>
      <webElementGuid>8df24bc0-54f6-4470-a4c9-1a9de62474f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/workflow/')]</value>
      <webElementGuid>14ded734-5999-4ba4-8424-717fca3a80d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>7abb3ebe-4c71-4617-a1e8-73daf7078908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/workflow/' and (text() = 'LISSIAflow' or . = 'LISSIAflow')]</value>
      <webElementGuid>84c7f970-d41a-49b6-9387-a69cf12e35ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
