<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Please Select --    AA    AE    A_2f9a67</name>
   <tag></tag>
   <elementGuidId>937c185d-b094-43f2-bc1a-ffa2179869b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowDetails_input_itemMetadata_25__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='workflowDetails_input_itemMetadata_25__value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4b372e90-f4fe-4850-997a-17829c218774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>itemMetadata[25].value</value>
      <webElementGuid>8587b00d-e255-47c1-b571-9aed00e88a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowDetails_input_itemMetadata_25__value</value>
      <webElementGuid>8888da99-efe9-4c78-9321-a8b4459ac493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>setFocusField(this);</value>
      <webElementGuid>cfdf8802-e5c6-41f0-9ab9-1baa36fe1d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>refreshMetadataDisplay(this, &quot;481&quot;, &quot;false&quot;, &quot;80946&quot;)</value>
      <webElementGuid>67cda7f8-b50f-49a1-9931-a460379fe903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bs-select-hidden</value>
      <webElementGuid>14284da7-6cb9-4e60-a034-f3a408eadbc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    -- Please Select --
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


</value>
      <webElementGuid>e6b1ee55-f223-46d5-8e2a-4bc66cf2ce8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowDetails_input_itemMetadata_25__value&quot;)</value>
      <webElementGuid>b811ed79-1d97-48fc-b851-3aef39170ed8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='workflowDetails_input_itemMetadata_25__value']</value>
      <webElementGuid>df0eda27-a409-4fd1-b45f-2391e0fa5813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_workflowDetails_input_itemMetadata_25__value']/select</value>
      <webElementGuid>9628dfd4-c8fe-49e0-b9d1-9b80efbf941a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[1]</value>
      <webElementGuid>941b7241-8823-4f0b-9b2a-686e3f67e9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>53380947-a845-4402-b17e-620e8239fa6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Please Select --'])[4]/preceding::select[1]</value>
      <webElementGuid>59d8c099-41e9-49d6-a917-5d6dc983e5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-- Please Select --'])[5]/preceding::select[1]</value>
      <webElementGuid>ee1a6521-6d0c-4a54-b4a3-2e9ab1ba10bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[2]/div/div/div/div/select</value>
      <webElementGuid>ebbe3a42-a88d-4341-bbd2-49cad96bc880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'itemMetadata[25].value' and @id = 'workflowDetails_input_itemMetadata_25__value' and (text() = '
    -- Please Select --
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


' or . = '
    -- Please Select --
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


')]</value>
      <webElementGuid>2f14b18e-0a3f-40d0-9f1e-2afb96dbfd64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
