<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nothing found to display_methodexecuteOnce</name>
   <tag></tag>
   <elementGuidId>790f3273-46cb-4529-805f-1cea9d9b6738</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startInterview_startInterview_submit_save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startInterview_startInterview_submit_save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4c969df-7825-4254-8e76-486203d8dbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8f1cd038-a642-42b7-8a43-1280305450c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Start ></value>
      <webElementGuid>92d8cefa-dc5b-4206-8511-e7c926432bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startInterview_startInterview_submit_save</value>
      <webElementGuid>0a9927cd-55f3-4e67-b69a-7a1d2a8f76bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>method:executeOnce</value>
      <webElementGuid>269d99d3-8e2c-4a4c-a703-18d3ec70f507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right el-button ui-state-default ui-corner-all ui-button ui-widget ui-state-hover ui-state-focus</value>
      <webElementGuid>94f0192a-e6f8-4e63-81ba-6fa27396cc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>60f966b9-aec5-4762-b355-f08bcb8f167b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af7e19b4-2db1-4eb7-8811-d5c38c99b8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startInterview_startInterview_submit_save&quot;)</value>
      <webElementGuid>0302891c-4dbb-4ff0-84cc-40c05f597007</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startInterview_startInterview_submit_save']</value>
      <webElementGuid>38160ee5-24b7-4edb-a5f3-91d9f783b94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wwctrl_startInterview_startInterview_submit_save']/input</value>
      <webElementGuid>cef9d7de-21e7-43cc-b3ef-112db204feec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>39e6046f-41ae-4183-ae06-99f194d302f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'startInterview_startInterview_submit_save' and @name = 'method:executeOnce']</value>
      <webElementGuid>711f30d5-ddeb-4dcf-9529-3e78094db3bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
