<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Document ID_interview.readOnlyScores0_ebbbaa</name>
   <tag></tag>
   <elementGuidId>bf396f50-773c-4577-90a8-c8b81cc92002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='startInterview_interview_readOnlyScores_0__totalString']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#startInterview_interview_readOnlyScores_0__totalString</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6de76ebd-d131-4402-898a-133d71f33526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44796092-a72c-4483-81ff-b9f6f543f31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>interview.readOnlyScores[0].totalString</value>
      <webElementGuid>640f228a-bbad-4590-b64d-0b824d38100f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>startInterview_interview_readOnlyScores_0__totalString</value>
      <webElementGuid>46044734-fd19-4fcf-a62b-0b053bcade27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;startInterview_interview_readOnlyScores_0__totalString&quot;)</value>
      <webElementGuid>2757ccd0-24e3-4a48-8f39-13417c20926a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='startInterview_interview_readOnlyScores_0__totalString']</value>
      <webElementGuid>5f668ef3-5157-46ae-b155-99bd232efe23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='score']/tbody/tr/td[3]/input</value>
      <webElementGuid>d1713901-d098-46b7-9ac2-536a614dd936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>4f11c721-9772-4602-9cf1-21fcf662d531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'interview.readOnlyScores[0].totalString' and @id = 'startInterview_interview_readOnlyScores_0__totalString']</value>
      <webElementGuid>64033b77-911c-4adb-8c57-a96ea4665eb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
