<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CB1 Email</name>
   <tag></tag>
   <elementGuidId>2955ab91-2fd1-4c1d-9640-3702281e5bb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_CB_Email_1']/div/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element-Q_CB_Email_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fc77b18-3cd7-4d1e-8f3b-96203e780d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4773b2b3-e2ff-4b9f-984f-1c736ef7fafc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[33].answers[0].value</value>
      <webElementGuid>78de3b59-520f-41d5-ac65-09b17b637ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_CB_Email_1</value>
      <webElementGuid>99fef334-4d4c-448f-8a5e-7c6a580788f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>aa389638-706f-4d10-bdd1-74a8bc5e88a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_CB_Email_1&quot;)</value>
      <webElementGuid>bbc352b1-b199-426f-97fe-46601236f9f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_CB_Email_1']</value>
      <webElementGuid>fb005d35-34b4-4d53-b7f8-ab50debd6005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_CB_Email_1']/div/div[2]/div/div/input</value>
      <webElementGuid>0464e989-afef-49ed-ae03-3e5610151b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[15]/div/div/div[2]/div/div/input</value>
      <webElementGuid>adbee0e3-f08d-4ca3-b952-4bc22842047a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[33].answers[0].value' and @id = 'element-Q_CB_Email_1']</value>
      <webElementGuid>fdde7126-e5d6-4583-bfa7-ff41ba7d9a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
