<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CB1 Address Line 1</name>
   <tag></tag>
   <elementGuidId>4fcc8c6d-9e0d-43bc-89ea-7394c27f6a4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_CB_Address_1']/div/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element-Q_CB_Address_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91285dba-9731-4ac7-ac7d-f11cd1e181fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9be3776-9877-4190-a1b2-66f32c16d51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[28].answers[0].value</value>
      <webElementGuid>59f1edf3-a4cc-4fa4-94eb-22fd6522909f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_CB_Address_1</value>
      <webElementGuid>62e4f8f0-7e35-44dc-bb63-c6c446258e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control</value>
      <webElementGuid>221313f6-8ab5-46cc-80ba-6a3ac2fdd713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_CB_Address_1&quot;)</value>
      <webElementGuid>79a28061-d5da-42a0-919b-3a43e60a26ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_CB_Address_1']</value>
      <webElementGuid>c211b9be-4ff9-41fb-8456-47085e90fe78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_CB_Address_1']/div/div[2]/div/div/input</value>
      <webElementGuid>0f2af746-c3b1-47c8-af7c-54f5c5754e94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[10]/div/div/div[2]/div/div/input</value>
      <webElementGuid>0877f6e6-9f42-44aa-9fe8-15510a4feb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[28].answers[0].value' and @id = 'element-Q_CB_Address_1']</value>
      <webElementGuid>5cc2d759-1327-42b7-9718-2c9f35606903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
