<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CB1 Zip Code</name>
   <tag></tag>
   <elementGuidId>9b35549d-44ea-440e-b09b-c24ad8ed8208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_CB_Zip_1']/div/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element-Q_CB_Zip_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab01cd7c-ff23-4531-9da9-acf0a48dd551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca0bfbfb-452e-4319-b0b8-3ba25de88de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[32].answers[0].value</value>
      <webElementGuid>84353535-ed61-4a33-a8e7-5e897f5620e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_CB_Zip_1</value>
      <webElementGuid>1c608989-ebcf-4e27-8bba-e32b6a414ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control placeholderColor</value>
      <webElementGuid>a842eaa4-b4f7-44c6-8c8c-38a4eedbad5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxxx</value>
      <webElementGuid>1f56941e-f49a-422a-8197-ae66d66c1e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_CB_Zip_1&quot;)</value>
      <webElementGuid>8fb04f0b-30a0-402b-b44f-d454cfe3b242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_CB_Zip_1']</value>
      <webElementGuid>72a56bbc-69cb-4b85-b55c-2bf39b79b753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_CB_Zip_1']/div/div[2]/div/div/input</value>
      <webElementGuid>55fe0c08-3921-4cfe-98c7-43f425e154d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[14]/div/div/div[2]/div/div/input</value>
      <webElementGuid>68627e9f-4417-4cc6-b070-3c882d53cab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[32].answers[0].value' and @id = 'element-Q_CB_Zip_1' and @placeholder = 'xxxxx']</value>
      <webElementGuid>0b1b114c-6901-4085-9f8d-37dae2504206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
