<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Continue button</name>
   <tag></tag>
   <elementGuidId>2131f808-ee10-4219-8777-a3eeff013bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_nextPageContinue_execute</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46b477b2-fd99-4e84-b5de-1af463ba2c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>27a51015-cf2d-46ab-8f4a-b4856191501d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_nextPageContinue_execute</value>
      <webElementGuid>084c4d0a-dace-4ac1-b028-0754110b7152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>action:nextPageContinue!execute</value>
      <webElementGuid>43ba2c6e-69a1-4eae-80c5-28d72b6f0d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Continue ></value>
      <webElementGuid>ec89c9b4-44d4-4f9d-9dc6-bad75a1bfb90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> btn btn-primary</value>
      <webElementGuid>f9943bdb-4e21-4e6f-97c2-b0096c115c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_nextPageContinue_execute&quot;)</value>
      <webElementGuid>8e3874e0-15a2-404e-a454-83429986a96b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_nextPageContinue_execute']</value>
      <webElementGuid>3002fdc6-4e56-41b1-98ec-fd7c576b573b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-continue']/input</value>
      <webElementGuid>dbcb55ec-33e3-43e7-9dbc-ab6a80ae57c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>dd7f517b-e148-46ff-9cb2-9837dfe893cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'el-content-form_nextPageContinue_execute' and @name = 'action:nextPageContinue!execute']</value>
      <webElementGuid>3da8ec92-1945-41be-acab-22b4a8d6ef2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
