<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PB1 State</name>
   <tag></tag>
   <elementGuidId>41f91dfe-9cb0-4d07-bacc-eb59c9a83f4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_PB_State_1']/div/div[2]/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_currentPage_allQuestions_12__answers_0__value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>02a2d54e-88f7-4b23-be1b-8d6371188a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[12].answers[0].value</value>
      <webElementGuid>bdddfd0d-09f6-468a-a485-14589fc1937d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_currentPage_allQuestions_12__answers_0__value</value>
      <webElementGuid>29560883-86d1-4f91-934f-aebc019f9197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-block form-control</value>
      <webElementGuid>ae883858-56b7-43f4-9a82-4ddaa9f12cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>conditionallyAutoContinue(false);</value>
      <webElementGuid>18d5c327-0f25-464d-a468-0a0fab9fe79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    Please Select
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


</value>
      <webElementGuid>46bdcbd0-4907-461a-979e-6f1578863511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_currentPage_allQuestions_12__answers_0__value&quot;)</value>
      <webElementGuid>3f715b2c-c2be-489c-9332-73804a4c76cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='el-content-form_currentPage_allQuestions_12__answers_0__value']</value>
      <webElementGuid>8c78f21e-4578-4bb7-b008-4422f225a079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_PB_State_1']/div/div[2]/div/div/select</value>
      <webElementGuid>dc37ea51-a740-40a6-aaab-a7bda1ee9a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::select[1]</value>
      <webElementGuid>5d241b58-9552-4c0f-b151-57bd75df5151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>d8038a88-acce-4912-b4b4-5b714655b380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[1]/preceding::select[1]</value>
      <webElementGuid>e06f4b6d-fdac-4993-9a96-554b0425a4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/preceding::select[1]</value>
      <webElementGuid>fcd14f72-3e01-470e-8d82-69f0c6ee2525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/div/select</value>
      <webElementGuid>69578363-47f3-4e39-9243-6fbdb44cc836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currentPage.allQuestions[12].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_12__answers_0__value' and (text() = '
    Please Select
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


' or . = '
    Please Select
    AA
    AE
    AK
    AL
    AP
    AR
    AS
    AZ
    CA
    CO
    CT
    DC
    DE
    FL
    FM
    GA
    GU
    HI
    IA
    ID
    IL
    IN
    KS
    KY
    LA
    MA
    MD
    ME
    MH
    MI
    MN
    MO
    MP
    MS
    MT
    NC
    ND
    NE
    NH
    NJ
    NM
    NV
    NY
    OH
    OK
    OR
    PA
    PR
    PW
    RI
    SC
    SD
    TN
    TX
    UT
    VA
    VI
    VT
    WA
    WI
    WV
    WY


')]</value>
      <webElementGuid>1dac5c97-9d2e-4670-8106-3c1d6058fbef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
