<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PB1 Zip Code</name>
   <tag></tag>
   <elementGuidId>ad37316e-ec58-4fcb-8587-e7639f9e2c24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_PB_Zip_1']/div/div[2]/div/div/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#element-Q_PB_Zip_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3378071-27b4-4d2d-aa49-899c441424bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>237cbb1a-f602-4d39-bc73-1bb96941f506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[12].answers[0].value</value>
      <webElementGuid>717b4079-a6ce-46d3-91fc-69836437dccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>element-Q_PB_Zip_1</value>
      <webElementGuid>1350efae-e3ed-46f3-9144-9517859c9ebd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>output form-control placeholderColor</value>
      <webElementGuid>30466cb4-992f-49fe-b558-a3e98a3317ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxxx</value>
      <webElementGuid>db55a776-0c79-4e1f-9404-7f85c6c2c9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;element-Q_PB_Zip_1&quot;)</value>
      <webElementGuid>2a21875b-72d1-4a73-8e3d-30c583bbba38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='element-Q_PB_Zip_1']</value>
      <webElementGuid>2f3abfe1-5c0c-4b1b-9e7a-464ba05f628f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_PB_Zip_1']/div/div[2]/div/div/input</value>
      <webElementGuid>38564c91-9c1d-497a-84ba-eb0a99a81ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div/div[2]/div/div/input</value>
      <webElementGuid>afd4d706-64b4-45d0-af86-a760551096f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[12].answers[0].value' and @id = 'element-Q_PB_Zip_1' and @placeholder = 'xxxxx']</value>
      <webElementGuid>c52cac2c-b2b6-4bc4-b064-29d18d078857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
