<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Date of Discharge</name>
   <tag></tag>
   <elementGuidId>8d7ba57b-f2e1-4af8-a0ee-310e5a06a26d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#el-content-form_currentPage_allQuestions_0__answers_0__value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_DofDischarge']/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81a750bf-93a8-4b9b-8f14-40d1e4a41c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bdaf6082-650a-4765-ace9-240355cf5804</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[0].answers[0].value</value>
      <webElementGuid>a6426202-382b-4bf1-989d-61b0494d9fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>el-content-form_currentPage_allQuestions_0__answers_0__value</value>
      <webElementGuid>8467a643-a1c6-423b-a7db-2b049ccfe5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker align-text-center form-control hasDatepicker</value>
      <webElementGuid>0c749e81-8090-47b7-b664-b546ff5274b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-content-form_currentPage_allQuestions_0__answers_0__value&quot;)</value>
      <webElementGuid>f2410904-cdd2-4f70-9eda-8d84b2b437d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='el-content-form_currentPage_allQuestions_0__answers_0__value']</value>
      <webElementGuid>454bc161-ac21-44e4-b16c-6e80d0a40151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_DofDischarge']/div/div[2]/div/div/input</value>
      <webElementGuid>0f00ca97-1b8c-4870-86c6-f8977618bbd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>ca81623b-3de5-42e8-a854-14aa9e367f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'currentPage.allQuestions[0].answers[0].value' and @id = 'el-content-form_currentPage_allQuestions_0__answers_0__value']</value>
      <webElementGuid>833edef4-1ea4-40b4-8bdb-6771ee5c63b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
