<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ServiceConnectedDisabilityGranted Yes</name>
   <tag></tag>
   <elementGuidId>aafc6194-4a74-408c-aa7e-28b92d932964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-qag-Q_SerConnectDis']/div/div[2]/div/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>449319c2-2719-4916-91de-016bf75258c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7282855c-f175-4684-9db8-7dd27c0f92a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c85b85d8-c4fa-4af7-aad9-8853e23fe0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currentPage.allQuestions[2].answers[0].value</value>
      <webElementGuid>56e5da33-dddd-4d68-914e-3efebe977d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currentPage.allQuestions[2].answers[0].value-1</value>
      <webElementGuid>6486e210-7174-44bc-b692-eea1482ae7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>efda9cd7-74cf-4b8b-8042-22ee3c21d7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>conditionallyAutoContinue(false);</value>
      <webElementGuid>a3e6fe31-f3cb-4243-b63c-df557f7be830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currentPage.allQuestions[2].answers[0].value-1&quot;)</value>
      <webElementGuid>8ef95283-48f6-4df6-a9ea-d026a4bb7242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currentPage.allQuestions[2].answers[0].value-1']</value>
      <webElementGuid>3f3be451-ba91-4287-b31b-ecc396b80971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-qag-Q_SerConnectDis']/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>4636bd68-0b90-4ee3-baa5-64e5d605076e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>9f948bf9-b65c-4ac4-9921-387fdb112425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'currentPage.allQuestions[2].answers[0].value' and @id = 'currentPage.allQuestions[2].answers[0].value-1']</value>
      <webElementGuid>32cfca82-9086-4d55-864c-5568d8a3e286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
